### PR TITLE
136 development refactoring lunchmenu comment

### PR DESCRIPTION
**Pull request by nlom0218**
resolve #149

### CODE REVIEW

**Review by nlom0218 — COMMENTED** [review]
굿굿!

**Review by SHJcompany — COMMENTED** [review]
승인합니다!

**Review by teacher-kiwi — APPROVED** [review]
OK!

**Comment by soave424** [comment]
comment

**Review by SHJcompany — APPROVED** [review]
승인합니다!

**Review by soave424 — APPROVED** [review]
승인

**Comment by anomist3** [comment]
Great!

**Pull request merged**
